apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed-app
  namespace: dev
  labels:
    app: sosmed
spec:
  # modify replicas according to your case
  replicas: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sosmed
  template:
    metadata:
      labels:
        app: sosmed
    spec:
      containers:
      - name: sosmed-app
        image: angeloken/test:DOCKER_TAG
        ports: 
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-rahasia
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: secret-rahasia
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secret-rahasia
              key: MYSQL_USER
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: secret-rahasia
              key: DB_HOST
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: secret-rahasia
              key: DB_PASS
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-rahasia
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret-rahasia
              key: DB_NAME