apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed-app
  namespace: dev
  labels:
    app: sosmed
spec:
  # modify replicas according to your case
  replicas: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sosmed
  template:
    metadata:
      labels:
        app: sosmed
    spec:
      containers:
      - name: sosmed-app
        image: unsyncxed/example:latest
        ports: 
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: cfgmap-sosmed
          - secretRef:
              name: secret-sosmed