apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed-app
  namespace: dev
  labels:
    app: sosmed
spec:
  # modify replicas according to your case
  replicas: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sosmed
  template:
    metadata:
      labels:
        app: sosmed
    spec:
      containers:
      - name: sosmed-app
        image: angeloken/test:DOCKER_TAG
        ports: 
        - containerPort: 80
        env:
          - name: DB_PASS #pass secret
            valueFrom:
              secretKeyRef:
                name: secret-rahasia
                key: DB_PASS
          - name: DB_USER #user secret
            valueFrom:
              secretKeyRef:
                name: secret-rahasia
                key: DB_USER
          - name: DB_HOST #configmap
            valueFrom:
              configMapKeyRef:
                name: configmap-sql
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: configmap-sql
                key: DB_NAME