apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed-app-v2
  namespace: dev
  labels:
    app: sosmed
spec:
  # modify replicas according to your case
  replicas: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sosmed
  template:
    metadata:
      labels:
        app: sosmed
    spec:
      containers:
      - name: sosmed-app-v2
        image: angeloken/test:DOCKER_TAG
        ports: 
        - containerPort: 80