apiVersion: v1
kind: PersistentVolume
metadata:
  name: sosmed-volume
  namespace: dev
spec:
  storageClassName: storage-sosmed
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /data/location