apiVersion: v1
kind: Secret
metadata:
  name: secret-rahasia
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Admin123
  MYSQL_DATABASE: kel2db
  MYSQL_USER: u01
  DB_HOST: mysqlkel2
  DB_PASS: Admin123 
  DB_USER: u01 
  DB_NAME: kel2db