apiVersion: v1
kind: Service
metadata:
  name: svc-sosmed
  namespace: dev
  labels:
    app: sosmed
spec:
  type: NodePort
  selector:
    app: sosmed
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082

---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  namespace: dev
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306

