apiVersion: v1
kind: Service
metadata:
  name: svc-sosmed
  namespace: dev
  labels:
    app: sosmed
spec:
  type: NodePort
  selector:
    app: sosmed
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082