apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1
  namespace: dev
  labels:
    app: sosmed
spec:
  accessModes:
    - ReadWriteOnce  #ini artinya misal kita replica pod nya 3 cuma 1 yg connect, duanya bakal pending statusnya kalau mau semua rwmany
  storageClassName: storage-sosmed
  resources:
    requests:
      storage: 1Gi

---
piVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed-app
  namespace: dev
  labels:
    app: sosmed
spec:
  # modify replicas according to your case
  replicas: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sosmed
  template:
    metadata:
      labels:
        app: sosmed
    spec:
      initContainers:
      - name: sosmed
        image: unsyncxed/example:latest
        ports: 
        - containerPort: 80
        volumeMounts: 
        - name: config-volume
          mountPath: /data
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: vol1

---
apiVersion: v1
kind: Service
metadata:
  name: svc-sosmed
  namespace: dev
  labels:
    app: sosmed
spec:
  type: NodePort
  selector:
    app: sosmed
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082