apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-db
  namespace: dev
  labels:
    app: mysql
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: sqldb
        image: angeloken/test:testsql
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: config-volume
        ports: 
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: Admin123
          - name: MYSQL_DATABASE
            value: kel2db
          - name: MYSQL_USER
            value: u01
          - name: MYSQL_PASSWORD
            value: Admin123
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: sosmed-volume-claim