apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-db
  namespace: dev
  labels:
    app: sosmed
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: sqldb
        image: angeloken/test:testsql
        ports: 
        - containerPort: 3306
        envFrom:
          - configMapRef:
              name: cfgmap-sql
          - secretRef:
              name: secret-sql
        volumeMounts: 
        - name: config-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: sosmed-volume-claim